
\@setckpt{hoofdstuk_02}{
\@setckpt{hoofdstuk_03}{
\@setckpt{hoofdstuk_04}{
\@setckpt{pagnum}{
\@writefile{lof}{\contentsline {figure}{\numberline {1}{\ignorespaces Schema}}{4}{figure.0.1}}
\@writefile{lof}{\contentsline {figure}{\numberline {2}{\ignorespaces PCB ontwerp}}{4}{figure.0.2}}
\@writefile{lof}{\contentsline {figure}{\numberline {3}{\ignorespaces RS485}}{6}{figure.0.3}}
\@writefile{lof}{\select@language{dutch}}
\@writefile{lof}{\select@language{dutch}}
\@writefile{lot}{\select@language{dutch}}
\@writefile{lot}{\select@language{dutch}}
\@writefile{toc}{\select@language{dutch}}
\@writefile{toc}{\select@language{dutch}}
\AtEndDocument{\let \contentsline\oldcontentsline
\catcode`"\active
\else
\fi
\gdef \contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\gdef \newlabel#1#2{\newlabelxx{#1}#2}
\gdef \newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\global \let \hyper@last\relax 
\global \let \oldcontentsline\contentsline
\global \let \oldnewlabel\newlabel
\ifx\hyper@anchor\@undefined
\let \newlabel\oldnewlabel}
\newlabel{fig:PNG}
\newlabel{fig:PNG}
\newlabel{fig:PNG}
\select@language{dutch}
\select@language{dutch}
\setcounter{ALC@depth}{0}
\setcounter{ALC@depth}{0}
\setcounter{ALC@depth}{0}
\setcounter{ALC@depth}{0}
\setcounter{ALC@line}{0}
\setcounter{ALC@line}{0}
\setcounter{ALC@line}{0}
\setcounter{ALC@line}{0}
\setcounter{ALC@rem}{0}
\setcounter{ALC@rem}{0}
\setcounter{ALC@rem}{0}
\setcounter{ALC@rem}{0}
\setcounter{ALC@unique}{0}
\setcounter{ALC@unique}{0}
\setcounter{ALC@unique}{0}
\setcounter{ALC@unique}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Hfootnote}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{Item}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{chapter}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumiii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumii}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumiv}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{enumi}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{equation}{0}
\setcounter{figure}{0}
\setcounter{figure}{2}
\setcounter{figure}{3}
\setcounter{figure}{3}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{footnote}{0}
\setcounter{lstlisting}{0}
\setcounter{lstlisting}{0}
\setcounter{lstlisting}{0}
\setcounter{lstlisting}{0}
\setcounter{lstnumber}{1}
\setcounter{lstnumber}{1}
\setcounter{lstnumber}{1}
\setcounter{lstnumber}{1}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{mpfootnote}{0}
\setcounter{page}{1}
\setcounter{page}{6}
\setcounter{page}{7}
\setcounter{page}{8}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{paragraph}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{part}{0}
\setcounter{r@tfl@t}{0}
\setcounter{r@tfl@t}{0}
\setcounter{r@tfl@t}{0}
\setcounter{r@tfl@t}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section@level}{0}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{section}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subparagraph}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{subsubsection}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
\setcounter{table}{0}
}
}
}
}
